<a href="https://colab.research.google.com/github/shauryakohli/trial/blob/main/MINOR_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install ipython-autotime
%load_ext autotime

time: 194 µs


In [3]:
!pip install bing-image-downloader

time: 2.74 s


In [4]:
!mkdir images

time: 110 ms


In [125]:
from bing_image_downloader import downloader
downloader.download("dog",limit=30,output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 13 Images on Page 1.


[%] Downloading Image #1 from http://2.bp.blogspot.com/-9QaOdl2TjiQ/ULXmDxMf6tI/AAAAAAAAEAU/PlPzEYknG4M/s1600/white_dog_blue_eyes.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://www.top13.net/wp-content/uploads/2015/11/perfectly-timed-dog-pictures-5.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.sunnyskyz.com/uploads/2014/08/eiuhg-cat-standing22.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://hative.com/wp-content/uploads/2014/10/cool-pet-costumes/12-cool-pet-costumes.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://messagenote.com/wp-content/uploads/2015/09/StarBarks.jpg
[%] File Downloaded !

[%] Downloading Image #6 from http://www.recreoviral.com/wp-content/uploads/2015/02/cute-animals-in-cups-49__700-563x750.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://weneedfun.com/wp-content/uploads/2016/08/Tumblr-Ocean-Backgrounds-6.jpg
[%] File D

In [55]:
from bing_image_downloader import downloader
downloader.download("laptop",limit=30,output_dir='images',adult_filter_off=True)

[!] Issue getting: https://wallpapersite.com/images/wallpapers/vr-concept-1440x2560-virtual-reality-headset-203.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://wallpapersite.com/images/wallpapers/shadow-of-the-colossus-1440x2560-playstation-4-2018-4k-8k-10917.jpg
[!] Issue getting: https://wallpapersite.com/images/wallpapers/shadow-of-the-colossus-1440x2560-playstation-4-2018-4k-8k-10917.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://wallpapersite.com/images/wallpapers/poppy-field-1440x2560-sunset-red-poppies-hd-5k-3197.jpg
[!] Issue getting: https://wallpapersite.com/images/wallpapers/poppy-field-1440x2560-sunset-red-poppies-hd-5k-3197.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://wallpapersite.com/images/wallpapers/yennefer-1440x2560-gwent-the-witcher-card-game-4k-8k-8257.jpg
[!] Issue getting: https://wallpapersite.com/images/wallpapers/yennefer-1440x2560-gwent-the-witcher-card-game-4k

KeyboardInterrupt: ignored

time: 15.2 s


In [68]:
from bing_image_downloader import downloader
downloader.download("sunflower",limit=30,output_dir='images',adult_filter_off=True)



[!!]Indexing page: 1

[%] Indexed 13 Images on Page 1.


[%] Downloading Image #1 from https://wallpapersite.com/images/wallpapers/peter-rabbit-1440x2560-animation-adventure-comedy-2018-hd-4k-11354.jpg
[!] Issue getting: https://wallpapersite.com/images/wallpapers/peter-rabbit-1440x2560-animation-adventure-comedy-2018-hd-4k-11354.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://wallpapersite.com/images/wallpapers/winter-mountains-720x1280-lake-forest-pine-trees-hd-4831.jpg
[!] Issue getting: https://wallpapersite.com/images/wallpapers/winter-mountains-720x1280-lake-forest-pine-trees-hd-4831.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading Image #1 from https://wallpapersite.com/images/wallpapers/peter-rabbit-1440x2560-animation-adventure-comedy-2018-5k-11913.jpg
[!] Issue getting: https://wallpapersite.com/images/wallpapers/peter-rabbit-1440x2560-animation-adventure-comedy-2018-5k-11913.jpg
[!] Error:: HTTP Error 404: Not Found
[%] Downloading 

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

time: 10.7 ms


In [126]:
#PreProcessing
import os
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
from skimage.transform import resize
target = []
images=[]
flat_data =[]
DATADIR = '/content/images'
CATEGORIES=['dog','laptop','sunflower']
for category in CATEGORIES:
      class_num=CATEGORIES.index(category)#LabelEncoding values
      path = os.path.join(DATADIR,category)#Path to store all images
      for img in os.listdir(path):
       img_array = imread(os.path.join(path,img))
       img_resized = resize(img_array,(150,150,3))  # 0-255 will be normalized 0-1
       flat_data.append(img_resized.flatten())
       images.append(img_resized)
       target.append(class_num)
      
flat_data=np.array(flat_data)
target=np.array(target)
images=np.array(images)



time: 59.5 s


In [127]:
flat_data[0]

array([0.1372549 , 0.09803922, 0.08616993, ..., 0.04324183, 0.0471634 ,
       0.05511111])

time: 3.31 ms


In [128]:
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

time: 3.55 ms


In [129]:
unique,count=np.unique(target,return_counts=True)
plt.bar(CATEGORIES,count)

<BarContainer object of 3 artists>

time: 128 ms


In [130]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size=0.7,random_state=109)

time: 27.8 ms


In [131]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000],'kernel':['linear']},
               {'C':[1,10,100,1000],'gamma':[0.001,0.0001],'kernel':['rbf']}
    ]

svc=svm.SVC(probability=True)
clf=GridSearchCV(svc,parameters)
clf.fit(x_train,y_train)


GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['rbf']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

time: 22.6 s


In [132]:
y_pred=clf.predict(x_test)
y_pred


array([0, 0, 1, 2, 2, 1, 0, 0, 1, 0, 1, 0, 0, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 0, 0, 0, 2, 1, 1, 2, 0, 2, 2,
       0, 0, 2, 0, 2, 1, 0, 0, 0, 1, 0, 1, 2, 2, 2, 2, 2, 2, 0])

time: 198 ms


In [133]:
y_test

array([1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 1, 2, 1, 0, 1, 2, 2,
       2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1, 2, 0, 2, 2,
       0, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 1, 0, 2, 2, 2, 2, 2, 0])

time: 3.25 ms


In [134]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


time: 1.15 ms


In [135]:
accuracy_score(y_pred,y_test)

0.8571428571428571

time: 7.6 ms


In [136]:
confusion_matrix(y_pred,y_test)

array([[19,  4,  3],
       [ 0, 17,  0],
       [ 2,  0, 18]])

time: 7.39 ms


In [137]:
#Save the model using pickel library
import pickle
pickle.dump(clf,open('img_model.p','wb'))

time: 26.1 ms


In [138]:
model=pickle.load(open('img_model.p','rb'))

time: 12.7 ms


In [144]:
#Testing a brand new image
flat_data=[]
url=input('Enter your URL')
img=imread(url)
img_resized=resize(img,(150,150,3))
flat_data.append(img_resized.flatten())
flat_data=np.array(flat_data)
print(img.shape)
plt.imshow(img_resized)
y_out=model.predict(flat_data)
y_out=CATEGORIES[y_out[0]]
print(f'PREDICTED OUTPUT: {y_out}')


Enter your URLhttps://www.treehugger.com/thmb/z3hnJHKMZuISWB2JJ51GoqXHk3U=/1899x1424/smart/filters:no_upscale()/GettyImages-561348663-85fe7dfbcf354dc19216589c7609f5c1.jpg
(1424, 1899, 3)
PREDICTED OUTPUT: sunflower


time: 6.47 s
